services:
  - type: web
    name: attendance-backend
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: cd backend && gunicorn edurfid.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: '*'
      - key: DJANGO_ALLOWED_HOSTS
        value: '*'
      - key: DATABASE_URL
        sync: false

  - type: web
    name: attendance-frontend
    env: static
    plan: free
    buildCommand: cd frontend/react_app && npm install && npm run build
    staticPublishPath: frontend/react_app/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: attendance-backend
          property: url
