services:
  - type: web
    name: attendance-backend
    env: docker
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: '*'
      - key: DJANGO_ALLOWED_HOSTS
        value: '*'
      - key: DATABASE_URL
        sync: false

  - type: static
    name: attendance-frontend
    buildCommand: export REACT_APP_API_URL="https://${BACKEND_HOST}/api" && cd frontend/react_app && npm install && npm run build
    staticPublishPath: frontend/react_app/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: BACKEND_HOST
        fromService:
          type: web
          name: attendance-backend
          property: host
